<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>The information of the clients with diabets </title>
</head>
<body>
<h1><strong>There are 8 clients with diabets in the database.</strong></h1>
<blockquote>
<p><strong><FirstName>FirstName:Agnes</FirstName>,
		<LastName>LastName:Israel</LastName>,
		<Age>Age:30</Age>,
		</strong></p>
<p><em><Surgries>Surgries:Fallopian Tube Cancer</Surgries>,
			<Immunization_status>Immunization_status:Active</Immunization_status></em></p>
<br><p><strong><FirstName>FirstName:Andrew</FirstName>,
		<LastName>LastName:Mathew</LastName>,
		<Age>Age:43</Age>,
		</strong></p>
<p><em><Surgries>Surgries:Otolaryngology</Surgries>,
			<Immunization_status>Immunization_status:Active</Immunization_status></em></p>
<br><p><strong><FirstName>FirstName:Ashiat</FirstName>,
		<LastName>LastName:Adeogun</LastName>,
		<Age>Age:30</Age>,
		</strong></p>
<p><em><Surgries>Surgries:Optician</Surgries>,
			<Immunization_status>Immunization_status:Active</Immunization_status></em></p>
<br><p><strong><FirstName>FirstName:Bola</FirstName>,
		<LastName>LastName:Tola</LastName>,
		<Age>Age:37</Age>,
		</strong></p>
<p><em><Surgries>Surgries:Cancer</Surgries>,
			<Immunization_status>Immunization_status:Active</Immunization_status></em></p>
<br><p><strong><FirstName>FirstName:Daniel</FirstName>,
		<LastName>LastName:Israel</LastName>,
		<Age>Age:30</Age>,
		</strong></p>
<p><em><Surgries>Surgries:BreastCancer</Surgries>,
			<Immunization_status>Immunization_status:Active</Immunization_status></em></p>
<br><p><strong><FirstName>FirstName:George</FirstName>,
		<LastName>LastName:Mathew</LastName>,
		<Age>Age:40</Age>,
		</strong></p>
<p><em><Surgries>Surgries:BreastCancer</Surgries>,
			<Immunization_status>Immunization_status:Active</Immunization_status></em></p>
<br><p><strong><FirstName>FirstName:Semase</FirstName>,
		<LastName>LastName:Balogun</LastName>,
		<Age>Age:25</Age>,
		</strong></p>
<p><em><Surgries>Surgries:None</Surgries>,
			<Immunization_status>Immunization_status:Active</Immunization_status></em></p>
<br><p><strong><FirstName>FirstName:Sodipo</FirstName>,
		<LastName>LastName:James</LastName>,
		<Age>Age:30</Age>,
		</strong></p>
<p><em><Surgries>Surgries:CervicalCancer</Surgries>,
			<Immunization_status>Immunization_status:Active</Immunization_status></em></p>
<br><p><strong><FirstName>FirstName:Sunita</FirstName>,
		<LastName>LastName:Pandey</LastName>,
		<Age>Age:38</Age>,
		</strong></p>
<p><em><Surgries>Surgries:BreastCancer</Surgries>,
			<Immunization_status>Immunization_status:Active</Immunization_status></em></p>
<br><p><strong><FirstName>FirstName:Tinuoluwa</FirstName>,
		<LastName>LastName:Balogun</LastName>,
		<Age>Age:36</Age>,
		</strong></p>
<p><em><Surgries>Surgries:None</Surgries>,
			<Immunization_status>Immunization_status:Active</Immunization_status></em></p>
<br><p><strong><FirstName>FirstName:Wanu</FirstName>,
		<LastName>LastName:Pandey</LastName>,
		<Age>Age:30</Age>,
		</strong></p>
<p><em><Surgries>Surgries:BreastCancer</Surgries>,
			<Immunization_status>Immunization_status:Active</Immunization_status></em></p>
<br>
</blockquote>
</body>
</html>
